/**
 * Progress metrics → docs/PROGRESS.md. See docs/METRICS.md for definitions.
 *   pnpm metrics          write docs/PROGRESS.md and print a summary
 *   pnpm metrics --check  compute and print only (CI)
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { join, resolve } from 'node:path';
import { countLines, flattenLines, wordCount } from '@perde/shared';
import { packs } from '@perde/content';

const root = resolve(import.meta.dirname, '..');
const check = process.argv.includes('--check');

interface Milestone {
  title: string;
  done: number;
  total: number;
  open: string[];
}

function roadmap(): Milestone[] {
  const text = readFileSync(join(root, 'docs/ROADMAP.md'), 'utf8');
  const out: Milestone[] = [];
  let cur: Milestone | null = null;
  for (const line of text.split('\n')) {
    const h = /^## (.+?)\s*(✅)?\s*$/.exec(line);
    if (h) {
      cur = { title: h[1]!.trim(), done: 0, total: 0, open: [] };
      out.push(cur);
      continue;
    }
    const box = /^- \[( |x|X)\] (.+)$/.exec(line);
    if (box && cur) {
      cur.total++;
      if (box[1]!.toLowerCase() === 'x') cur.done++;
      else cur.open.push(box[2]!.trim());
    }
  }
  return out;
}

function walk(dir: string, pred: (p: string) => boolean, acc: string[] = []): string[] {
  if (!existsSync(dir)) return acc;
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry === 'dist' || entry === '.wrangler') continue;
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) walk(p, pred, acc);
    else if (pred(p)) acc.push(p);
  }
  return acc;
}

function countMatches(files: string[], re: RegExp): number {
  return files.reduce((n, f) => n + (readFileSync(f, 'utf8').match(re)?.length ?? 0), 0);
}

function bundleGzipKb(): number | null {
  const dir = join(root, 'apps/web/dist/assets');
  if (!existsSync(dir)) return null;
  const js = readdirSync(dir).filter((f) => f.endsWith('.js'));
  if (!js.length) return null;
  return Math.max(...js.map((f) => gzipSync(readFileSync(join(dir, f))).length)) / 1024;
}

function bar(done: number, total: number, width = 20): string {
  const filled = total ? Math.round((done / total) * width) : 0;
  return '█'.repeat(filled) + '░'.repeat(width - filled);
}

const ms = roadmap();
const done = ms.reduce((n, m) => n + m.done, 0);
const total = ms.reduce((n, m) => n + m.total, 0);
const current = ms.find((m) => m.done < m.total);

const plays = packs.flatMap((p) => p.plays);
const puppets = packs.flatMap((p) => p.puppets);
const lines = plays.flatMap((p) => flattenLines(p).map((l) => l.line.text));
const shortLines = lines.filter((t) => wordCount(t) <= 14).length;
const avgWords = lines.length ? lines.reduce((n, t) => n + wordCount(t), 0) / lines.length : 0;

const srcFiles = walk(root, (p) => /\.(ts|tsx|mjs)$/.test(p) && !p.includes('/scripts/metrics.ts'));
const unitTests = countMatches(
  srcFiles.filter((p) => p.endsWith('.test.ts')),
  /\bit\(/g,
);
const e2eTests = countMatches(
  walk(join(root, 'e2e'), (p) => p.endsWith('.spec.ts')),
  /\btest\(/g,
);
const todos = countMatches(
  srcFiles.filter((p) => !p.endsWith('.test.ts')),
  /\b(TODO|FIXME)\b/g,
);
const decisions = existsSync(join(root, 'docs/decisions'))
  ? readdirSync(join(root, 'docs/decisions')).filter((f) => /^\d{4}-.*\.md$/.test(f)).length
  : 0;
const playtests = existsSync(join(root, 'docs/PLAYTESTS.md'))
  ? (readFileSync(join(root, 'docs/PLAYTESTS.md'), 'utf8').match(/^## \d{4}-\d{2}-\d{2}/gm)
      ?.length ?? 0)
  : 0;
const gz = bundleGzipKb();

const rows: Array<[string, string]> = [
  ['Roadmap completion', `${done}/${total} (${total ? Math.round((done / total) * 100) : 0} %)`],
  ['Current milestone', current ? current.title : 'all milestones done'],
  [
    'Packs / puppets / plays / lines',
    `${packs.length} / ${puppets.length} / ${plays.length} / ${lines.length}`,
  ],
  [
    'Free plays · Plus plays',
    `${plays.filter((p) => !p.premium).length} · ${plays.filter((p) => p.premium).length}`,
  ],
  [
    'Free puppets · Plus puppets',
    `${puppets.filter((p) => !p.premium).length} · ${puppets.filter((p) => p.premium).length}`,
  ],
  [
    'Kid-friendly lines (≤ 14 words)',
    `${shortLines}/${lines.length} (${lines.length ? Math.round((shortLines / lines.length) * 100) : 0} %)`,
  ],
  ['Average words per line', avgWords.toFixed(1)],
  ['Unit tests · e2e tests', `${unitTests} · ${e2eTests}`],
  ['Web bundle (largest chunk, gzip)', gz == null ? 'run pnpm build' : `${gz.toFixed(0)} kB`],
  ['Open TODOs in source', String(todos)],
  ['Decisions recorded', String(decisions)],
  ['Playtests logged', String(playtests)],
];

const md = [
  '# Progress',
  '',
  `_Generated by \`pnpm metrics\` on ${new Date().toISOString().slice(0, 10)}. Definitions in [METRICS.md](METRICS.md); milestones in [ROADMAP.md](ROADMAP.md)._`,
  '',
  '| metric | value |',
  '| --- | --- |',
  ...rows.map(([k, v]) => `| ${k} | ${v} |`),
  '',
  '## Milestones',
  '',
  '| milestone | progress | |',
  '| --- | --- | --- |',
  ...ms.map((m) => `| ${m.title} | \`${bar(m.done, m.total)}\` | ${m.done}/${m.total} |`),
  '',
  '## Next up',
  '',
  ...(current
    ? current.open.slice(0, 3).map((o) => `- ${o}`)
    : ['- Nothing open. Add the next milestone to ROADMAP.md.']),
  '',
  '## Plays',
  '',
  '| culture | play | lines | minutes | tier |',
  '| --- | --- | --- | --- | --- |',
  ...plays.map(
    (p) =>
      `| ${p.cultureId} | ${p.title} | ${countLines(p)} | ${p.durationMin} | ${p.premium ? 'Plus' : 'free'} |`,
  ),
  '',
].join('\n');

console.log(rows.map(([k, v]) => `${k.padEnd(34)} ${v}`).join('\n'));
console.log(
  '\n' +
    ms.map((m) => `${m.title.padEnd(44)} ${bar(m.done, m.total)} ${m.done}/${m.total}`).join('\n'),
);
if (!check) {
  writeFileSync(join(root, 'docs/PROGRESS.md'), md);
  console.log('\nwrote docs/PROGRESS.md');
}
